### PR TITLE
Update options.dtd

### PR DESCRIPTION
**Pull request by skywinds5012**
try to correct the confusing words

### CODE REVIEW

**Comment by yfdyh000** [comment]
Please update them on http://zoo.darktrojan.net/darktrojan/newtabtools/zh-CN/locale.php

However, I don't understand why does these changes, can you explain in more details? 可以用中文。

**Comment by skywinds5012** [comment]
嗯，重新研读了一下这个选项，我发现我可能产生了一些误解。
这个应该不是翻译上的问题了，而是代码自身的问题了。
现在的情况是，预料中打勾就能“固定磁贴并移除磁贴按钮”，而去掉勾才能实现这个效果。
麻烦确认一下这个问题。以及这个pull request可以关掉了。另一边的issue看来也需要修改一下。

**Comment by yfdyh000** [comment]
仔细研究了一下，的确是颠倒的。看到了，是#84吧。提交了补丁，等待审核。

**Comment by darktrojan** [comment]
@yfdyh000 You're the only person that can make changes on Zoo. I admit that is a bit stupid, but that's the way it is for now.

**Comment by yfdyh000** [comment]
@darktrojan Okay, this restriction does not seem so obvious, but I know now.

**Pull request closed without merging**
